[package]
name = "rust-gemini"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
thiserror = "1.0.63"
tokio = "1.39.2"
